name: build
on:
    push:
        branches:
            - main
        tags:
            - '[0-9]+*'
    schedule:
        -   cron: '0 6 * * *'
    workflow_dispatch:

concurrency:
    cancel-in-progress: true
    group: ${{ github.workflow }}-${{ github.ref }}

permissions:
    packages: write

env:
    TAGS: ${{ format('ghcr.io/{0}:{1}', github.repository, startsWith(github.ref, 'refs/tags/') && github.ref_name || 'dev') }}

    VIPS_VERSION: 8.15.3

    PHP_VERSION: 8.3.11
    FRANKENPHP_VERSION: 1.2.5

    GRAALVM_VERSION: 22.3.3
    PDFTK_VERSION: 3.3.3

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    ref: 'main'

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Cache Docker layers
                uses: actions/cache@v4
                with:
                    path: /tmp/.buildx-cache
                    key: "buildx-${{ hashFiles('Dockerfile') }}-${{ github.run_id }}"
                    restore-keys: |
                        buildx-${{ hashFiles('Dockerfile') }}
                        buildx-

            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build base image
                uses: docker/build-push-action@v6
                with:
                    provenance: false
                    context: .
                    push: true
                    file: Dockerfile
                    platforms: linux/amd64, linux/arm64
                    build-args: |
                        "VIPS_VERSION=${{ env.VIPS_VERSION }}"
                        
                        "PHP_VERSION=${{ env.PHP_VERSION }}"
                        "FRANKENPHP_VERSION=${{ env.FRANKENPHP_VERSION }}"
                        
                        "GRAALVM_VERSION=${{ env.GRAALVM_VERSION }}"
                        "PDFTK_VERSION=${{ env.PDFTK_VERSION }}"
                    tags: ${{ env.TAGS }}
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

            -   name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache
